# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='goal',
            name='onDate',
            field=models.DateField(blank=True),
        ),
    ]
